export default[
    {
        "color-scheme": "light",
        "primary": "#34d399",
        "primary-content": "#064e3b",
        "secondary": "#60a5fa",
        "accent": "#f9a8d4",
        "neutral": "#d1d5db",
        "base-100": "#f3f4f6",
        "info": "#3b82f6",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "error": "#ef4444",
        "theme": "light"
      },
      {
        "color-scheme": "dark",
        "primary": "#9333ea",
        "primary-content": "#faf5ff",
        "secondary": "#fb7185",
        "accent": "#facc15",
        "neutral": "#1f2937",
        "base-100": "#111827",
        "info": "#38bdf8",
        "success": "#10b981",
        "warning": "#fbbf24",
        "error": "#ef4444",
        "theme": "dark"
      },
      {
        "color-scheme": "cupcake",
        "primary": "#fbbf24",
        "primary-content": "#78350f",
        "secondary": "#f472b6",
        "accent": "#c4b5fd",
        "neutral": "#f3f4f6",
        "base-100": "#ffffff",
        "info": "#2563eb",
        "success": "#16a34a",
        "warning": "#f59e0b",
        "error": "#e11d48",
        "theme": "cupcake"
      },
      {
        "color-scheme": "retro",
        "primary": "#eab308",
        "primary-content": "#78350f",
        "secondary": "#facc15",
        "accent": "#f43f5e",
        "neutral": "#64748b",
        "base-100": "#e5e7eb",
        "info": "#2563eb",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "error": "#ef4444",
        "theme": "retro"
      },
      {
        "color-scheme": "forest",
        "primary": "#14532d",
        "primary-content": "#a7f3d0",
        "secondary": "#1e293b",
        "accent": "#d9f99d",
        "neutral": "#064e3b",
        "base-100": "#d1fae5",
        "info": "#3b82f6",
        "success": "#4ade80",
        "warning": "#f59e0b",
        "error": "#ef4444",
        "theme": "forest"
      },
      {
        "color-scheme": "aqua",
        "primary": "#06b6d4",
        "primary-content": "#083344",
        "secondary": "#67e8f9",
        "accent": "#a5f3fc",
        "neutral": "#164e63",
        "base-100": "#f0fdfa",
        "info": "#2563eb",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "error": "#f87171",
        "theme": "aqua"
      },
      {
        "color-scheme": "cyberpunk",
        "primary": "#f43f5e",
        "primary-content": "#3f0f3f",
        "secondary": "#ec4899",
        "accent": "#8b5cf6",
        "neutral": "#111827",
        "base-100": "#f3f4f6",
        "info": "#38bdf8",
        "success": "#4ade80",
        "warning": "#f59e0b",
        "error": "#ef4444",
        "theme": "cyberpunk"
      },
      {
        "color-scheme": "pastel",
        "primary": "#fbcfe8",
        "primary-content": "#831843",
        "secondary": "#fde68a",
        "accent": "#bbf7d0",
        "neutral": "#d1fae5",
        "base-100": "#ffffff",
        "info": "#bfdbfe",
        "success": "#a7f3d0",
        "warning": "#fef08a",
        "error": "#fecaca",
        "theme": "pastel"
      },
      {
        "color-scheme": "valentine",
        "primary": "#ec4899",
        "primary-content": "#9d174d",
        "secondary": "#f472b6",
        "accent": "#fbcfe8",
        "neutral": "#fee2e2",
        "base-100": "#fdf2f8",
        "info": "#c4b5fd",
        "success": "#f9a8d4",
        "warning": "#fde047",
        "error": "#f43f5e",
        "theme": "valentine"
      },
      {
        "color-scheme": "halloween",
        "primary": "#f97316",
        "primary-content": "#7c2d12",
        "secondary": "#fb923c",
        "accent": "#78350f",
        "neutral": "#1c1917",
        "base-100": "#f5f5f4",
        "info": "#2563eb",
        "success": "#16a34a",
        "warning": "#facc15",
        "error": "#dc2626",
        "theme": "halloween"
      }
      
]